  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@postgres:5432/mydatabase"
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app
    command: ["npm", "run", "dev"]
    restart: unless-stopped
